language: node_js
node_js:
  - 8.11
before_install:
  - npm i -g npm@6.0.0
env:
  - NO_SANDBOX=true
install: npm ci
script:
  - npm run test
  - npm run build
  - npm run test:e2e:ci
  - npm run bundlesize
